# automatically generated by the FlatBuffers compiler, do not modify

# namespace: epd

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EpdFont(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsEpdFont(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EpdFont()
        x.Init(buf, n + offset)
        return x

    # EpdFont
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EpdFont
    def Bitmap(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # EpdFont
    def BitmapAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # EpdFont
    def BitmapLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EpdFont
    def BitmapIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # EpdFont
    def Glyph(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 16
            from epd.EpdGlyph import EpdGlyph
            obj = EpdGlyph()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EpdFont
    def GlyphLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EpdFont
    def GlyphIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # EpdFont
    def Intervals(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 12
            from epd.EpdUnicodeInterval import EpdUnicodeInterval
            obj = EpdUnicodeInterval()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EpdFont
    def IntervalsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EpdFont
    def IntervalsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # EpdFont
    def AdvanceY(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EpdFont
    def Ascender(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EpdFont
    def Descender(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # EpdFont
    def Is2bit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def EpdFontStart(builder): builder.StartObject(7)
def EpdFontAddBitmap(builder, bitmap): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(bitmap), 0)
def EpdFontStartBitmapVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def EpdFontAddGlyph(builder, glyph): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(glyph), 0)
def EpdFontStartGlyphVector(builder, numElems): return builder.StartVector(16, numElems, 4)
def EpdFontAddIntervals(builder, intervals): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(intervals), 0)
def EpdFontStartIntervalsVector(builder, numElems): return builder.StartVector(12, numElems, 4)
def EpdFontAddAdvanceY(builder, advanceY): builder.PrependUint8Slot(3, advanceY, 0)
def EpdFontAddAscender(builder, ascender): builder.PrependInt32Slot(4, ascender, 0)
def EpdFontAddDescender(builder, descender): builder.PrependInt32Slot(5, descender, 0)
def EpdFontAddIs2bit(builder, is2bit): builder.PrependBoolSlot(6, is2bit, 0)
def EpdFontEnd(builder): return builder.EndObject()
