# automatically generated by the FlatBuffers compiler, do not modify

# namespace: epd

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EpdGlyph(object):
    __slots__ = ['_tab']

    # EpdGlyph
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EpdGlyph
    def Width(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # EpdGlyph
    def Height(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(1))
    # EpdGlyph
    def AdvanceX(self): return self._tab.Get(flatbuffers.number_types.Uint8Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))
    # EpdGlyph
    def Left(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # EpdGlyph
    def Top(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(6))
    # EpdGlyph
    def DataLength(self): return self._tab.Get(flatbuffers.number_types.Uint16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))
    # EpdGlyph
    def DataOffset(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(12))

def CreateEpdGlyph(builder, width, height, advanceX, left, top, dataLength, dataOffset):
    builder.Prep(4, 16)
    builder.PrependUint32(dataOffset)
    builder.Pad(2)
    builder.PrependUint16(dataLength)
    builder.PrependInt16(top)
    builder.PrependInt16(left)
    builder.Pad(1)
    builder.PrependUint8(advanceX)
    builder.PrependUint8(height)
    builder.PrependUint8(width)
    return builder.Offset()
