# automatically generated by the FlatBuffers compiler, do not modify

# namespace: epd

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EpdGlyph(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EpdGlyph()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEpdGlyph(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EpdGlyph
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EpdGlyph
    def Width(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EpdGlyph
    def Height(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EpdGlyph
    def AdvanceX(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EpdGlyph
    def Left(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # EpdGlyph
    def Top(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int16Flags, o + self._tab.Pos)
        return 0

    # EpdGlyph
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # EpdGlyph
    def DataOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def EpdGlyphStart(builder):
    builder.StartObject(7)

def Start(builder):
    EpdGlyphStart(builder)

def EpdGlyphAddWidth(builder, width):
    builder.PrependUint8Slot(0, width, 0)

def AddWidth(builder, width):
    EpdGlyphAddWidth(builder, width)

def EpdGlyphAddHeight(builder, height):
    builder.PrependUint8Slot(1, height, 0)

def AddHeight(builder, height):
    EpdGlyphAddHeight(builder, height)

def EpdGlyphAddAdvanceX(builder, advanceX):
    builder.PrependUint8Slot(2, advanceX, 0)

def AddAdvanceX(builder, advanceX):
    EpdGlyphAddAdvanceX(builder, advanceX)

def EpdGlyphAddLeft(builder, left):
    builder.PrependInt16Slot(3, left, 0)

def AddLeft(builder, left):
    EpdGlyphAddLeft(builder, left)

def EpdGlyphAddTop(builder, top):
    builder.PrependInt16Slot(4, top, 0)

def AddTop(builder, top):
    EpdGlyphAddTop(builder, top)

def EpdGlyphAddDataLength(builder, dataLength):
    builder.PrependUint16Slot(5, dataLength, 0)

def AddDataLength(builder, dataLength):
    EpdGlyphAddDataLength(builder, dataLength)

def EpdGlyphAddDataOffset(builder, dataOffset):
    builder.PrependUint32Slot(6, dataOffset, 0)

def AddDataOffset(builder, dataOffset):
    EpdGlyphAddDataOffset(builder, dataOffset)

def EpdGlyphEnd(builder):
    return builder.EndObject()

def End(builder):
    return EpdGlyphEnd(builder)
