# automatically generated by the FlatBuffers compiler, do not modify

# namespace: epd

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EpdUnicodeInterval(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 12

    # EpdUnicodeInterval
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EpdUnicodeInterval
    def First(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # EpdUnicodeInterval
    def Last(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))
    # EpdUnicodeInterval
    def Offset(self): return self._tab.Get(flatbuffers.number_types.Uint32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(8))

def CreateEpdUnicodeInterval(builder, first, last, offset):
    builder.Prep(4, 12)
    builder.PrependUint32(offset)
    builder.PrependUint32(last)
    builder.PrependUint32(first)
    return builder.Offset()
